if(NOT WIN32)
  string(ASCII 27 Esc)
  set(ColourReset "${Esc}[m")
  set(ColourBold  "${Esc}[1m")
  set(Red         "${Esc}[31m")
  set(Green       "${Esc}[32m")
  set(Yellow      "${Esc}[33m")
  set(Blue        "${Esc}[34m")
  set(Magenta     "${Esc}[35m")
  set(Cyan        "${Esc}[36m")
  set(White       "${Esc}[37m")
  set(BoldRed     "${Esc}[1;31m")
  set(BoldGreen   "${Esc}[1;32m")
  set(BoldYellow  "${Esc}[1;33m")
  set(BoldBlue    "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan    "${Esc}[1;36m")
  set(BoldWhite   "${Esc}[1;37m")
endif()


macro (ilm_version)
  file(READ openexr/IlmBase/configure.ac CONFIGURE_AC_CONTENTS)
  string(REGEX MATCH "AC_INIT\\(IlmBase,[ ]*([0-9]+).([0-9]+).([0-9]+)" DUMMY ${CONFIGURE_AC_CONTENTS})
  set(ILMBASE_VERSION_MAJOR ${CMAKE_MATCH_1})
  set(ILMBASE_VERSION_MINOR ${CMAKE_MATCH_2})
  set(ILMBASE_VERSION_PATCH ${CMAKE_MATCH_3})
  set(ILMBASE_VERSION       ${ILMBASE_VERSION_MAJOR}.${ILMBASE_VERSION_MINOR}.${ILMBASE_VERSION_PATCH})
  set(ILMBASE_VERSION_API   ${ILMBASE_VERSION_MAJOR}_${ILMBASE_VERSION_MINOR})
  string(REGEX MATCH "LIBTOOL_CURRENT=([0-9]+)" DUMMY ${CONFIGURE_AC_CONTENTS})
  set(ILMBASE_SOCURRENT ${CMAKE_MATCH_1})
  string(REGEX MATCH "LIBTOOL_REVISION=([0-9]+)" DUMMY ${CONFIGURE_AC_CONTENTS})
  set(ILMBASE_SOREVISION ${CMAKE_MATCH_1})
  string(REGEX MATCH "LIBTOOL_AGE=([0-9]+)" DUMMY ${CONFIGURE_AC_CONTENTS})
  set(ILMBASE_SOAGE ${CMAKE_MATCH_1})
  math(EXPR ILMBASE_SOVERSION "${ILMBASE_SOCURRENT} - ${ILMBASE_SOAGE}")
  set(ILMBASE_LIB_VERSION "${ILMBASE_SOVERSION}.${ILMBASE_SOAGE}.${ILMBASE_SOREVISION}")
  message(STATUS "${Green}Configure ILMBASE Version: ${ILMBASE_VERSION} Lib API: ${ILMBASE_LIB_VERSION}${ColourReset}")
  unset(CONFIGURE_AC_CONTENTS)
endmacro()